#!/usr/bin/env php
<?php
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

TheDeceased\PHParser\UI\CLI\CLI::run();
